version: "2"
services:
  app:
    image: golang:1.9-alpine
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
      - datadog

  redis:
    image: redis:4-alpine

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  datadog:
    build: datadog
    links:
     - redis
     - postgres
    environment:
     - DD_APM_ENABLED=true
     - API_KEY=62e6170081cd3db36d3792d61945a6fd
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
