version: "2"
services:
  app:
    image: golang:1.9-alpine
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
      # We need this line to simulate the agent running on the same host than our app
      - datadog:localhost

  redis:
    image: redis:4-alpine
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  datadog:
    build: datadog
    links:
     - redis
     - postgres
    environment:
     - DD_APM_ENABLED=true
     - API_KEY=06ece0149ad7d455febcfc5cb8811f27
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
